########################################################
###connect database info
########################################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/school?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    
#公共配置与profiles选择无关
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: wmq.fly.mybatis.entity
  mapperLocations: classpath:test/mybatis/mappers/*Mapper.xml 
  
server:
  port: 9999
    