########################################################
###connect database info
########################################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/school?characterEncoding=utf-8
    #url: jdbc:mysql://localhost:8066/test?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    
     ###自定义数据源
#    test1: 
#      url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: 1234
#      driver-class-name: com.mysql.jdbc.Driver
#    test2: 
#      url: jdbc:mysql://localhost:3306/test02?useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: 1234
#      driver-class-name: com.mysql.jdbc.Driver
      
########################################################
###jta-atomikos数据源配置信息
########################################################      
# Mysql 1
mysql: 
  datasource:
    test01:
      url: jdbc:mysql://localhost:3308/test01?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1

# Mysql 2
    test02:
      url: jdbc:mysql://localhost:3308/test02?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1 

########################################################
### 打印mybatis运行的sql语句
########################################################       
logging: 
  level:
#wmq.fly为*Mapper.java接口所在的包  
    wmq.fly: DEBUG
              
########################################################
###connect redis info redis配置信息
########################################################    
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
 
########################################################
### freemarker配置信息
########################################################  
  freemarker:
    request-context-attribute: request  #request访问request  页面获取方式： ${request.contextPath}
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
     #！！！！src/main/java 和 src/main/resources 下的文件在编译后会放到WEB-INF/classes路径下，默认的classpath是在这里！！！所以这里要加上classpath
    #template-loader-path: classpath:/templates
    template-loader-path: /freemarkerDemo/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
 # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**
    
########################################################
### solr配置信息
########################################################       
  data:
    solr:
      host: http://127.0.0.1:8088/solr     
    
#公共配置与profiles选择无关
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: wmq.fly.mybatis.entity
  mapperLocations: classpath:test/mybatis/mappers/*Mapper.xml 
 
########################################################
###服务配置，如果配置了项目名，此时访问需要带上项目名
########################################################   
server:
#端口号
  port: 9999
#项目名
#  context-path: /wmq
name: hello word

########################################################
###多环境配置
########################################################    
spring.profiles.active: pre
 
 
 